README.md
glances/config.json
glances/rootfs/etc/cont-init.d/glances.sh

Add option for specifying Influx DB protocol (`http` `https`)
Also resolves issue experienced in add on startup due to upstream issue.
#25

:ambulance: Add https/http for InfluxDB fixes #25

---

README.md

closes #27
Update readme to show config for access to Glances directly
#27

📚Update Readme for HA sensor caused by ingress

---

README.md

For those that are YAML-averse, or are trying to do as much in the UI as possible, added instructions for integrating Glances through the integration panel.

:books: Add integrations setup instructions.

---

README.md

Update the integration details for Glances as it is now from the panel only
#67

📚Update integration details

---

LICENSE.md
README.md
glances/.README.j2
glances/DOCS.md

Happy New Year

---

glances/Dockerfile
glances/build.json

Upgrade add-on base image to the latest greatest

Upgrade add-on base image to 9.1.0

---

glances/Dockerfile
glances/build.json

https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2

Upgrade add-on base image to 9.1.2

---

glances/config.json
glances/rootfs/etc/glances.conf

Map the media folder to monitor your movie / music / images library
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

Add media folder

---

glances/Dockerfile

:arrow_up: Upgrades python3 to 3.8.7-r1

---

glances/Dockerfile

⬆️ Upgrades python3 to 3.8.8-r0

---

glances/Dockerfile
glances/build.json

Upgrades add-on base image to v9.1.5

⬆️ Upgrades add-on base image to v9.1.5

---

glances/Dockerfile
glances/build.json

Upgrades add-on base image to v9.2.0

Upgrades add-on base image to v9.2.0

---

glances/Dockerfile

⬆️ Upgrades python3 to 3.8.10-r0

---

glances/Dockerfile
glances/build.json

Upgrades add-on base image to v9.2.2

⬆️ Upgrades add-on base image to v9.2.2

---

glances/config.json

🏎 Enable streaming mode for Ingress

---

glances/Dockerfile
glances/build.json

Upgrades add-on base image to 10.1.0

⬆️ Upgrades add-on base image to 10.1.0

---

glances/Dockerfile
glances/build.yaml

Upgrades add-on base image to 10.2.0

⬆️ Upgrades add-on base image to 10.2.0

---

glances/Dockerfile
glances/build.yaml

Upgrades add-on base image to 10.2.2

⬆️ Upgrades add-on base image to 10.2.2

---

glances/Dockerfile
glances/build.yaml

Upgrades add-on base image to 11.0.0

⬆️ Upgrades add-on base image to 11.0.0

---

LICENSE.md
README.md
glances/.README.j2
glances/DOCS.md

:fireworks: Updates maintenance/license year to 2022

---

glances/Dockerfile
glances/build.yaml

Upgrades add-on base image to 11.0.1

⬆️ Upgrades add-on base image to 11.0.1

---

glances/Dockerfile
glances/build.yaml

Upgrades add-on base image to 11.1.0

⬆️ Upgrades add-on base image to 11.1.0

---

.github/workflows/deploy.yaml
glances/build.yaml
glances/config.yaml

Sign add-on with Codenotary Community Attestation Service (CAS)

:lock: Sign add-on with Codenotary Community Attestation Service (CAS)

---

glances/DOCS.md

Use new My Home Assistant link format, making things just a little easier

:books: Use new My Home Assistant link format

---

glances/Dockerfile

⬆️ Upgrades python3 to 3.10.5-r0

---

glances/Dockerfile
glances/build.yaml

⬆️ Upgrades add-on base image to 12.2.2

---

glances/Dockerfile
glances/build.yaml

Upgrades add-on base image to 12.2.3

⬆️ Upgrades add-on base image to 12.2.3

---

glances/Dockerfile

⬆️ Upgrades nginx to 1.22.1-r0

---

glances/Dockerfile
glances/build.yaml

⬆️ Upgrades add-on base image to 12.2.6

---

glances/Dockerfile

⬆️ Upgrades python3 to 3.10.8-r0

---

glances/Dockerfile
glances/build.yaml

⬆️ Upgrades add-on base image to 12.2.7

---

glances/Dockerfile

⬆️ Upgrades python3 to 3.10.9-r0

---

glances/Dockerfile
glances/build.yaml

Upgrades add-on base image to 13.0.0; which is based on Alpine Linux 3.17

⬆️ Upgrades add-on base image to 13.0.0

---

LICENSE.md
README.md
glances/.README.j2
glances/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

glances/Dockerfile
glances/build.yaml

⬆️ Upgrades add-on base image to 13.1.3

---

glances/DOCS.md
glances/config.yaml
glances/rootfs/etc/cont-init.d/glances.sh

Fixes typos in the influx config, definitely works under v1.x, I don't have a v2 instance to test against so would suggest we push to edge and get users to test.
Documentation needs a revisit.
#325 325
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

🚑 Attempt to fix Influx Issues

---

glances/DOCS.md

> (Describe the changes and rationale behind them)
Fixes broken URLs and replaces **Configuration -> Integrations -> Glances** with **Settings -> Devices & Services -> Integrations**
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

Fix broken URLs

---

README.md
glances/build.yaml
glances/config.yaml

Drop support for armhf & i386

---

glances/rootfs/etc/cont-init.d/glances.sh

🔨 Update logging from file to console

🔨 Update logging from file to console

---

LICENSE.md
README.md
glances/.README.j2
glances/DOCS.md

:fireworks: Updates maintenance/license year to 2024

---

LICENSE.md
README.md
glances/.README.j2
glances/DOCS.md

:fireworks: Updates maintenance/license year to 2025
